#!/usr/bin/env node
// build-demo.mjs — bundles src/*.js into a single dependency-free browser script
// docs/arkmap.bundle.js for the demo viewer (GitHub Pages serves only docs/).
//
// Deterministic concatenation in dependency order. Handles exactly the module
// plumbing this package uses: single-line `import { ... } from '...';`,
// single-line `export { ... };`, and `export function` declarations.
// Re-run after any src/ change. Output exposes `globalThis.arkmap`.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

// dependency order (verified acyclic)
const ORDER = [
  'constants.js', 'arkadia.js', 'arkadia-transports.js', 'ansi-pal.js', 'opposite.js',
  'mudlet-dat.js', 'validate.js', 'checksum.js', 'stable-stringify.js',
  'canonicalize.js', 'dat-to-arkmap.js', 'arkmap-to-dat.js',
  'suppressors.js', 'transports.js', 'arkmap.js', 'graph.js', 'waypoints.js',
  'locale.js', 'diff.js', 'search-index.js', 'render-model.js', 'render-svg.js', 'render-png.js',
];

const FOOTER = `
globalThis.arkmap = {
  loadArkmap, saveArkmap, createEmptyMap,
  datToArkmap, arkmapToDat, readMudletDat, writeMudletDat,
  validate, addChecksums, verifyChecksums, checkSuppressorsInMap,
  isArkadiaMap, stableStringify,
  buildIndex, edgeWeight, neighborsOf,
  findPath, findRoute, planRoute, countSpecialSteps, searchRooms,
  validateTransports, normalizeTransports,
  addTransportChecksums, verifyTransportChecksums, buildTransportEdges,
  TRANSPORT_BOARDING_PENALTY, TRANSPORT_TIME_RATIO, TRANSPORT_DEFAULT_TIME,
  TRANSPORTS_FORMAT, TRANSPORTS_VERSION, ARKADIA_TRANSPORTS,
  encodeRoute, decodeRoute, ROUTE_CODE_PREFIX, ROUTE_CODE_MAX, WP_MAX,
  diffMaps,
  buildSearchIndex, searchIndexed,
  renderSvg, svgToPng, renderPng,
  RENDER_MODEL: {
    CELL, ROOM_UNITS, ROOM_HALF, DEFAULT_ROOM_RGB, LINE_CSS, ONE_WAY_FILL,
    CROSS_UNKNOWN_CSS, CL_DEFAULT_CSS, DOOR_CSS, HIDDEN_FADE, RASTER_LINE_ALPHA,
    LOD_MIN_CELL_PX, LOD_ROOMS_BUDGET, LOD_RASTER_CELL_PX, DIR_VEC, OPP_DIR, UDIO_DIRS,
    buildColorCache, roomColorCss, roomColorRgb, isRoomHidden, hiddenRoomStyle,
    contrastCss, symbolColorCss, symbolFillCss, classifyExit, edgePoint, lineWidthUnits,
    exitLineOp, crossArrowOp, stubOps, dashPattern, customLineOp, doorSquareOp,
    roomOp, innerTrianglesOp, symbolOp, seMarkerOp, gridStyle, lodMode, rasterModel,
    stackShadowsOp, specialCrossArrows,
  },
  ARKADIA_ENVS, ARKADIA_SYMBOLS, ARKADIA_ENV, envPaletteList,
  ANSI_PAL, ansiPaletteRgb, OPPOSITE,
  DIRS, DIR_BY_SHORT, DIR_BY_LONG, DIR_BY_IDX, DOOR_INT, DOOR_STR, LINE_INT, LINE_STR,
  FORMAT, FORMAT_VERSION,
  CHECKSUM_ALG: 'v4',
  MUDLET_DAT_READ_MAX: MUDLET_DAT_MAX_SUPPORTED_VERSION,
  MUDLET_DAT_WRITE_VERSION,
};
`;

const parts = ['// GENERATED by scripts/build-demo.mjs — DO NOT EDIT. Source: ../src/', ''];
for (const f of ORDER) {
  let src = readFileSync(join(ROOT, 'src', f), 'utf8');
  const out = [];
  for (const line of src.split('\n')) {
    if (/^import\s*\{.*\}\s*from\s*'.*';?\s*$/.test(line)) continue;  // drop single-line imports
    if (/^export\s*\{.*\};?\s*$/.test(line)) continue;                // drop export lists
    out.push(line.replace(/^export function /, 'function '));
  }
  parts.push(`// ── src/${f} ──`, ...out);
}
parts.push(FOOTER);
const bundle = parts.join('\n');
writeFileSync(join(ROOT, 'docs', 'arkmap.bundle.js'), bundle);
console.log(`wrote docs/arkmap.bundle.js (${bundle.length} B)`);
