#!/usr/bin/env node
// extract.mjs — deterministic extraction of the arkmap library modules from
// arkmap_studio.html (repo: Isithunzi000/arkadia-web_standalone-arkmap_studio).
//
// The single-file app is the source of truth. This script fetches it at a
// PINNED commit sha, verifies the source sha256, slices the verified line
// ranges, appends ESM plumbing (imports/exports — bodies stay verbatim),
// and writes src/*.js + EXTRACT_MANIFEST.json.
//
// Usage:
//   node scripts/extract.mjs            regenerate src/ + manifest
//   node scripts/extract.mjs --check    regenerate in memory, diff vs src/ (CI parity gate)
//
// Exit codes: 0 ok / 1 diff or mismatch. Fails closed on any drift.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_REPO = 'Isithunzi000/arkadia-web_standalone-arkmap_studio';
const SOURCE_FILE = 'arkmap_studio.html';
const SOURCE_SHA  = '24bd9022895753779758e5c58286565c76d85d19';
const SOURCE_SHA256 = '4a9523a1b348214115544514904bc97bdcb4527864b29dc1b2fce6192af6a061';

const sha256 = (s) => createHash('sha256').update(s, 'utf8').digest('hex');

// Verified line ranges (1-based, inclusive) @ SOURCE_SHA + ESM plumbing.
// imports/exports are appended by this script; block bodies stay byte-verbatim.
const BLOCKS = [
  { out: 'constants.js',       from: 4234,  to: 4278,
    exports: ['DIRS', 'DIR_BY_SHORT', 'DIR_BY_LONG', 'DIR_BY_IDX', 'DOOR_INT', 'DOOR_STR', 'DOOR_RGB', 'LINE_INT', 'LINE_STR', 'FORMAT', 'FORMAT_VERSION', '_ARKMAP_TOP_KEYS'] },
  { out: 'arkadia.js',         from: 4279,  to: 4431,
    exports: ['ARKADIA_ENVS', 'ARKADIA_SYMBOLS', 'envPaletteList', 'ARKADIA_ENV', 'ARKADIA_SIGNATURE_ENVS', 'isArkadiaMap'] },
  { out: 'validate.js',        from: 4434,  to: 4798,
    imports: [{ from: './constants.js', names: ['DIR_BY_SHORT', 'FORMAT', 'FORMAT_VERSION', 'LINE_INT'] }],
    exports: ['validate'] },
  { out: 'checksum.js',        from: 4799,  to: 5552,
    exports: ['xxh3_64', 'xxh3_64hex', 'addChecksums', 'verifyChecksums', '_stripRoomDefaults'] },
  { out: 'mudlet-dat.js',      from: 5553,  to: 6540,
    exports: ['readMudletDat', 'writeMudletDat', 'MUDLET_DAT_MAX_SUPPORTED_VERSION', 'MUDLET_DAT_WRITE_VERSION', 'uint8ToBase64', 'base64ToUint8'] },
  { out: 'dat-to-arkmap.js',   from: 6541,  to: 6769,
    imports: [{ from: './constants.js', names: ['DIRS', 'DIR_BY_LONG', 'DOOR_STR', 'FORMAT', 'FORMAT_VERSION', 'LINE_STR'] },
              { from: './arkadia.js',   names: ['isArkadiaMap'] },
              { from: './mudlet-dat.js', names: ['readMudletDat', 'uint8ToBase64'] }],
    exports: ['datToArkmap'] },
  { out: 'arkmap-to-dat.js',   from: 6770,  to: 6958,
    imports: [{ from: './constants.js', names: ['DIRS', 'DIR_BY_LONG', 'DIR_BY_SHORT', 'DOOR_INT', 'LINE_INT'] },
              { from: './ansi-pal.js',  names: ['ansiPaletteRgb'] },
              { from: './mudlet-dat.js', names: ['writeMudletDat', 'base64ToUint8'] }],
    exports: ['arkmapToDat'] },
  { out: 'ansi-pal.js',        from: 7201,  to: 7218,
    exports: ['ANSI_PAL', 'ansiPaletteRgb'] },
  { out: 'opposite.js',        from: 8049,  to: 8054,
    exports: ['OPPOSITE'] },
  { out: 'stable-stringify.js', from: 10512, to: 10535,
    exports: ['stableStringify'] },
  { out: 'canonicalize.js',    from: 10590, to: 10606,
    exports: ['_canonicalizeMapForSave'] },
  { out: 'suppressors.js',     from: 19357, to: 19413,
    imports: [{ from: './opposite.js', names: ['OPPOSITE'] }],
    exports: ['checkSuppressorsInMap', '_findMissingSuppressors'] },
];

function header(block) {
  return [
    `// GENERATED by scripts/extract.mjs — DO NOT EDIT.`,
    `// Source: ${SOURCE_REPO}/${SOURCE_FILE} @ ${SOURCE_SHA} (lines ${block.from}-${block.to})`,
    `// Bodies are byte-verbatim from the app; only import/export plumbing is added.`,
    ``,
  ].join('\n');
}

function render(block, lines) {
  const body = lines.slice(block.from - 1, block.to).join('\n').replace(/\s+$/, '');
  const parts = [header(block)];
  for (const imp of block.imports || []) {
    parts.push(`import { ${imp.names.join(', ')} } from '${imp.from}';`);
  }
  if (block.imports?.length) parts.push('');
  parts.push(body, '');
  parts.push(`export { ${block.exports.join(', ')} };`, '');
  return parts.join('\n');
}

async function main() {
  const check = process.argv.includes('--check');
  const url = `https://raw.githubusercontent.com/${SOURCE_REPO}/${SOURCE_SHA}/${SOURCE_FILE}`;
  const res = await fetch(url);
  if (!res.ok) { console.error(`fetch failed: HTTP ${res.status} (${url})`); process.exit(1); }
  const text = await res.text();
  const srcHash = sha256(text);
  if (srcHash !== SOURCE_SHA256) {
    console.error(`SOURCE MISMATCH: sha256 ${srcHash} != pinned ${SOURCE_SHA256}`);
    console.error('The source file drifted from the audited revision. Review and re-pin deliberately.');
    process.exit(1);
  }
  const lines = text.split('\n');

  const manifest = {
    source: { repo: SOURCE_REPO, file: SOURCE_FILE, sha: SOURCE_SHA, sha256: SOURCE_SHA256 },
    generated: {},
  };
  const outputs = new Map();
  for (const block of BLOCKS) {
    const content = render(block, lines);
    outputs.set(`src/${block.out}`, content);
    manifest.generated[`src/${block.out}`] = { lines: [block.from, block.to], sha256: sha256(content) };
  }
  const manifestText = JSON.stringify(manifest, null, 2) + '\n';
  outputs.set('EXTRACT_MANIFEST.json', manifestText);

  if (check) {
    let bad = 0;
    for (const [path, content] of outputs) {
      let existing;
      try { existing = readFileSync(join(ROOT, path), 'utf8'); }
      catch { console.error(`MISSING: ${path}`); bad++; continue; }
      if (existing !== content) { console.error(`DRIFT: ${path}`); bad++; }
    }
    // unexpected extra files in src/ (hand-written modules are allowed:
    // arkmap.js, index.js, graph.js, transports.js, arkadia-transports.js,
    // waypoints.js, diff.js, search-index.js, render-svg.js, render-png.js)
    const allowed = new Set([...outputs.keys()].map(p => p.replace(/^src\//, ''))
      .concat(['arkmap.js', 'index.js', 'graph.js', 'transports.js', 'arkadia-transports.js',
               'waypoints.js', 'diff.js', 'search-index.js', 'render-svg.js', 'render-png.js']));
    for (const f of readdirSync(join(ROOT, 'src'))) {
      if (!allowed.has(f)) { console.error(`UNEXPECTED: src/${f}`); bad++; }
    }
    if (bad) { console.error(`parity check FAILED (${bad} problem(s))`); process.exit(1); }
    console.log(`parity check OK — ${BLOCKS.length} modules byte-identical to source @ ${SOURCE_SHA.slice(0, 7)}`);
    return;
  }

  for (const [path, content] of outputs) {
    writeFileSync(join(ROOT, path), content);
    console.log(`wrote ${path} (${content.length} B)`);
  }
}

await main();
