// GENERATED by scripts/extract.mjs — DO NOT EDIT.
// Source: Isithunzi000/arkadia-web_standalone-arkmap_studio/arkmap_studio.html @ 24bd9022895753779758e5c58286565c76d85d19 (lines 7201-7218)
// Bodies are byte-verbatim from the app; only import/export plumbing is added.

// ─── COLOR CACHE ──────────────────────────────────────────────────────────────
// ANSI 256-colour palette
const ANSI_PAL = buildAnsiPal();
function buildAnsiPal() {
  const p = {};
  const sys = [[0,0,0],[128,0,0],[0,128,0],[128,128,0],[0,0,128],[128,0,128],[0,128,128],[192,192,192],
               [128,128,128],[255,0,0],[0,255,0],[255,255,0],[0,0,255],[255,0,255],[0,255,255],[255,255,255]];
  sys.forEach((c,i) => { p[i]=c; });
  const lv=[0,95,135,175,215,255];for(let i=16;i<=231;i++){const n=i-16;p[i]=[lv[Math.floor(n/36)%6],lv[Math.floor(n/6)%6],lv[n%6]];}
  for (let i=232;i<=255;i++){const v=8+(i-232)*10;p[i]=[v,v,v];}
  return p;
}
function ansiPaletteRgb(envId) {
  if (envId < 1 || envId > 255) return null;
  // Mudlet offset: envId 8 → ANSI 0 (black), envId 16 → ANSI 8 (bright black)
  const ansiIdx = envId === 8 ? 0 : envId === 16 ? 8 : envId;
  return ANSI_PAL[ansiIdx] ?? null;
}

export { ANSI_PAL, ansiPaletteRgb };
