// GENERATED by scripts/extract.mjs — DO NOT EDIT.
// Source: Isithunzi000/arkadia-web_standalone-arkmap_studio/arkmap_studio.html @ 24bd9022895753779758e5c58286565c76d85d19 (lines 4279-4431)
// Bodies are byte-verbatim from the app; only import/export plumbing is added.

// ── arkadia-env.js ──
/**
 * arkadia-env.js
 *
 * Słownik środowisk (envId → kolor + nazwa) i symboli pokoi dla świata Arkadia.
 * Wyprowadzony z projektu arkadia-crowdmap (Delwing/Dargoth) — de facto standard
 * używany przez kartografów Arkadii od lat.
 *
 * Źródło: draw_tools/gui/mapper tools.lua z arkadia-crowdmap-master
 */

// ─── ŚRODOWISKA ───────────────────────────────────────────────────────────────
// Mapa envId → { name, rgb: [r,g,b] }
// envId pochodzi z Mudlet (getCustomEnvColorTable / setRoomEnv)

const ARKADIA_ENVS = {
  200: { name: 'Fontanny / woda',     rgb: [0,   0,   255] },
  201: { name: 'env 201',             rgb: [0,   255, 0]   },
  202: { name: 'Bossowie / niebezp.', rgb: [255, 0,   0]   },
  203: { name: 'env 203',             rgb: [165, 42,  42]  },
  257: { name: 'Trakt',              rgb: [128, 0,   0]   },
  258: { name: 'Las',                rgb: [0,   179, 0]   },
  259: { name: 'env 259',            rgb: [128, 128, 0]   },
  260: { name: 'env 260',            rgb: [0,   0,   128] },
  261: { name: 'Bez światła',         rgb: [128, 0,   128] },
  262: { name: 'Wieś / Lok. łączona 2', rgb: [0,   128, 128] }, // env 262 używany dla Wieś i Lok. łączona 2
  263: { name: 'env 263',             rgb: [192, 192, 192] },
  264: { name: 'env 264',             rgb: [36,  36,  36]  },
  265: { name: 'env 265',             rgb: [255, 0,   0]   },
  266: { name: 'Kowale',              rgb: [0,   255, 0]   },
  267: { name: 'Dyliżanse / Porty',   rgb: [255, 255, 0]   },
  268: { name: 'Akweny wodne',        rgb: [0,   0,   255] },
  269: { name: 'Poczty',              rgb: [255, 0,   255] },
  270: { name: 'Lok. łączona 1',      rgb: [0,   255, 255] },
  271: { name: 'Startówka',           rgb: [255, 255, 255] },
  272: { name: 'Miasto',             rgb: [128, 128, 128] },
  293: { name: 'env 293',             rgb: [0,   171, 192] },
  294: { name: 'env 294',             rgb: [139, 255, 0]   },
  295: { name: 'Karczmy / budynki',   rgb: [239, 176, 73]  },
  296: { name: 'env 296',             rgb: [163, 151, 235] },
  297: { name: 'Lok. łączona 3',      rgb: [236, 167, 236] },
  298: { name: 'env 298',             rgb: [22,  232, 196] },
  299: { name: 'env 299',             rgb: [0,   170, 255] },
  300: { name: 'env 300',             rgb: [0,   196, 255] },
  301: { name: 'Góry z przepaścią',   rgb: [255, 114, 14]  },
  303: { name: 'Plaże / Góry',        rgb: [170, 139, 89]  },
  400: { name: 'env 400',             rgb: [186, 112, 74]  },
  798: { name: 'env 798',             rgb: [255, 140, 0]   },
  799: { name: 'env 799',             rgb: [230, 230, 250] },
  800: { name: 'env 800',             rgb: [30,  144, 255] },
  801: { name: 'env 801',             rgb: [154, 205, 50]  },
  802: { name: 'env 802',             rgb: [85,  107, 47]  },
  803: { name: 'env 803',             rgb: [0,   255, 255] },
  805: { name: 'env 805',             rgb: [107, 142, 35]  },
  806: { name: 'env 806',             rgb: [0,   100, 0]   },
  810: { name: 'env 810',             rgb: [255, 0,   0]   },
  811: { name: 'env 811',             rgb: [139, 69,  19]  },
  812: { name: 'env 812',             rgb: [230, 230, 250] },
  813: { name: 'env 813',             rgb: [255, 255, 255] },
  814: { name: 'env 814',             rgb: [34,  139, 34]  },
  815: { name: 'env 815',             rgb: [39,  227, 227] },
  823: { name: 'env 823',             rgb: [255, 215, 0]   },
  824: { name: 'env 824',             rgb: [47,  79,  79]  },
  825: { name: 'env 825',             rgb: [189, 183, 107] },
  826: { name: 'env 826',             rgb: [184, 134, 11]  },
  830: { name: 'env 830',             rgb: [255, 69,  0]   },
  855: { name: 'env 855',             rgb: [160, 82,  45]  },
};

// ─── SYMBOLE POKOJÓW ─────────────────────────────────────────────────────────
// Mapa symbol → opis (de facto standard arkadyjski, z crowdmap)
// roomChar / symbol w Mudlet to krótki string wyświetlany na mapie

const ARKADIA_SYMBOLS = {
  'P':  'Poczta',
  'K':  'Kowal',
  'S':  'Sklep / handlarz',
  's':  'Skup',
  'Z':  'Zielarz',
  'r':  'Rzemieślnik',
  'E':  'Trener zawodu',
  'T':  'Karczma',
  'p':  'Piekarnia',
  'a':  'Sprzedawca zwierząt',
  '[]': 'Tablica ogłoszeń',
  'm':  'Rzeźnik',
  'B':  'Biblioteka',
  'G':  'Gildia podróżnicza',
  'A':  'Aukcje / sklep gildiowy',
  'W':  'Wozownia',
  'u':  'Urna',
  'J':  'Jubiler / złotnik',
  '$':  'Bank / kantor',
  'C':  'Kasyno',
  'k':  'Krawiec',
  'F':  'Fryzjer',
  '+':  'Świątynia / kapliczka',
};

// Domyślne środowisko dla symbolu (>75% dominacji w mapie Arkadii + Zielarz)
const SYMBOL_DEFAULT_ENV = {
  'P': 269, 'K': 266, 'S': 295, 's': 295, 'Z': 258,
  'r': 295, 'T': 295, 'p': 295, 'a': 295, 'm': 295,
  'G': 295, 'J': 295, '$': 295, 'F': 295, 'k': 295,
  'u': 295, '+': 295,
};

/**
/**
 * Tablica środowisk jako lista do palety (sortowana po nazwie).
 * @returns {{ envId: number, name: string, rgb: number[] }[]}
 */
function envPaletteList() {
  return Object.entries(ARKADIA_ENVS)
    .map(([id, e]) => ({ envId: parseInt(id), name: e.name, rgb: e.rgb }))
    .sort((a, b) => a.name.localeCompare(b.name, 'pl'));
}



// Aliases expected by main script
const ARKADIA_ENV = Object.fromEntries(
  envPaletteList().map(e => [e.envId, { name: e.name, rgb: e.rgb }])
);

// ── Detekcja Arkadii (v1.43.3) ──────────────────────────────────────────────
// Mapy niosa wlasne kolory srodowisk (.dat v17+ w mCustomEnvColors / .arkmap
// colors.*), wiec tabela ARKADIA_ENVS/ARKADIA_SYMBOLS to override TYLKO dla map
// arkadianskich. true gdy: user_data.map_sync_version (marka mapsync) LUB
// 'arkadia' w nazwie mapy/pliku LUB >=2 sygnaturowe envId (>255, z tabeli)
// wsrod uzywanych envow pokoi albo kluczy kolorow z pliku. Czysta funkcja
// danych — ta sama mapa daje zawsze ten sam wynik.
const ARKADIA_SIGNATURE_ENVS = Object.keys(ARKADIA_ENVS).map(Number).filter(k => k > 255);
function isArkadiaMap(map, filename) {
  if (!map || typeof map !== 'object') return false;
  const ud = (map.meta && map.meta.user_data) || {};
  if (ud.map_sync_version !== undefined) return true;
  if (/arkadia/i.test(String(ud.map_name || '') + ' ' + String(filename || ''))) return true;
  const sig = new Set(ARKADIA_SIGNATURE_ENVS);
  const seen = new Set();
  let hits = 0;
  const bump = (k) => {
    k = Number(k);
    if (!sig.has(k) || seen.has(k)) return false;
    seen.add(k);
    return ++hits >= 2;
  };
  const cols = map.colors || {};
  for (const k of Object.keys(cols.custom_env_colors || {})) if (bump(k)) return true;
  for (const k of Object.keys(cols.env_colors || {})) if (bump(k)) return true;
  for (const a of map.areas || []) for (const r of a.rooms || []) if (bump(r.env)) return true;
  return false;
}

export { ARKADIA_ENVS, ARKADIA_SYMBOLS, envPaletteList, ARKADIA_ENV, ARKADIA_SIGNATURE_ENVS, isArkadiaMap };
