// GENERATED by scripts/extract.mjs — DO NOT EDIT.
// Source: Isithunzi000/arkadia-web_standalone-arkmap_studio/arkmap_studio.html @ 24bd9022895753779758e5c58286565c76d85d19 (lines 6770-6958)
// Bodies are byte-verbatim from the app; only import/export plumbing is added.

import { DIRS, DIR_BY_LONG, DIR_BY_SHORT, DOOR_INT, LINE_INT } from './constants.js';
import { ansiPaletteRgb } from './ansi-pal.js';
import { writeMudletDat, base64ToUint8 } from './mudlet-dat.js';

// ── arkmap-to-dat.js ──
// Converts .arkmap JSON -> Mudlet map.dat (Uint8Array).
// Browser version — uses mudlet_dat.js (no Node.js/require).


function toQColor(arr, defaultAlpha = 255) {
  if (!arr) return { spec: 1, r: 0, g: 0, b: 0, alpha: defaultAlpha, pad: 0 };
  return { spec: 1, r: arr[0], g: arr[1], b: arr[2], alpha: arr[3] ?? defaultAlpha, pad: 0 };
}

function toQFont(f) {
  if (!f) return null;
  let fontBits = 0;
  if (f.style_setting) fontBits |= 0x01;
  if (f.underline)     fontBits |= 0x02;
  if (f.strike_out)    fontBits |= 0x04;
  if (f.fixed_pitch)   fontBits |= 0x08;
  if (f.kerning !== false) fontBits |= 0x10;
  if (f.overline)      fontBits |= 0x40;
  if (f.style_oblique) fontBits |= 0x80;
  let extendedFontBits = 0;
  if (f.ignore_pitch)                extendedFontBits |= 0x01;
  if (f.letter_spacing_is_absolute)  extendedFontBits |= 0x02;
  return {
    family: f.family, style: f.style || '', pointSize: f.point_size, pixelSize: f.pixel_size,
    styleHint: f.style_hint, styleStrategy: f.style_strategy || 0, weight: f.weight,
    stretch: f.stretch ?? 100, letterSpacing: f.letter_spacing || 0, wordSpacing: f.word_spacing || 0,
    hintingPreference: f.hinting_preference || 0, capital: f.capital || 0,
    fontBits, extendedFontBits,
  };
}

function buildRoom(room, areaId) {
  const out = {
    area: areaId, x: room.x, y: room.y, z: room.z, environment: room.env,
    weight: room.weight ?? 1, name: room.name ?? '', isLocked: room.locked ?? false,
    symbol: room.symbol ?? '', userData: room.user_data ?? {},
  };
  if (room.hidden) out.hidden = true;  // audit T3/W4: hidden goes to raw — writeMudletRoom writes it to userData (v20 has no field)
  for (const { short, long } of DIRS) out[long] = room.exits?.[short] ?? -1;

  out.doors = {};
  for (const [key, val] of Object.entries(room.doors || {})) out.doors[key] = DOOR_INT[val] ?? 0;

  out.stubs = (room.stubs || []).map(s => DIR_BY_SHORT[s]?.idx).filter(Boolean).sort((a,b) => a - b);
  out.exitWeights = {};
  for (const [key, w] of Object.entries(room.exit_weights || {})) {
    const nk = DIR_BY_LONG[key] ? DIR_BY_LONG[key].short : key;  // audit T4: symmetry with the converter — long names do not go into .dat
    out.exitWeights[nk] = w;
  }
  out.exitLocks = (room.exit_locks || []).map(s => DIR_BY_SHORT[s]?.idx).filter(Boolean).sort((a,b) => a - b);

  const specialLockSet = new Set(room.special_exit_locks || []);
  out.rawSpecialExits = {};
  for (const [cmd, targetId] of Object.entries(room.special_exits || {})) {
    const prefix = specialLockSet.has(cmd) ? '1' : '0';
    if (!out.rawSpecialExits[targetId]) out.rawSpecialExits[targetId] = [];
    out.rawSpecialExits[targetId].push(prefix + cmd);
  }
  out.mSpecialExits = room.special_exits ?? {};
  out.mSpecialExitLocks = [...(room.special_exit_locks || [])];  // audit T4/C-locks: v21 semantics = a list of COMMANDS (strings); the writer reconstruction path does lockSet.has(cmd) — it used to look for strings among roomIds (latent mine)

  out.customLines = {}; out.customLinesArrow = {};
  out.customLinesColor = {}; out.customLinesStyle = {};
  for (const [key, cl] of Object.entries(room.custom_lines || {})) {
    out.customLines[key]      = (cl.points || []).map(p => [p[0], p[1]]);
    out.customLinesArrow[key] = cl.arrow ?? false;
    out.customLinesColor[key] = toQColor(cl.color || [255, 0, 0]);  // audit D-C1: default red per .arkmap spec (the datToArkmap reader also yields [255,0,0])
    out.customLinesStyle[key] = LINE_INT[cl.style] ?? LINE_INT.solid;
  }
  if (room.hash) out._hash = room.hash;
  return out;
}

function buildLabel(label) {
  return {
    id: label.id, pos: [label.x, label.y, label.z],
    size: [label.width, label.height], text: label.text,
    fgColor: toQColor(label.fg_color), bgColor: toQColor(label.bg_color),
    pixMap: label.pixmap ? base64ToUint8(label.pixmap) : new Uint8Array(0),
    noScaling: label.no_scaling ?? false, showOnTop: label.show_on_top ?? false,
  };
}

function arkmapToDat(arkmap) {
  const rooms = {}, areas = {}, areaNames = {}, labels = {}, mpRoomDbHashToRoomId = {};

  for (const area of arkmap.areas) {
    const areaId = area.id;
    areaNames[areaId] = area.name;
    const rawArea = {
      rooms: [], zLevels: [], mAreaExits: {},
      gridMode: area.grid_mode ?? false,
      max_x: 0, max_y: 0, max_z: 0, min_x: 0, min_y: 0, min_z: 0,
      span: [0, 0, 0],
      xmaxForZ: {}, ymaxForZ: {}, xminForZ: {}, yminForZ: {},
      pos: area.pos ?? [0, 0, 0],
      isZone: area.is_zone ?? false, zoneAreaRef: area.zone_area_ref ?? 0,
      userData: area.user_data ?? {},
    };

    for (const room of (area.rooms || [])) {
      const raw = buildRoom(room, areaId);
      raw._roomId = room.id;
      rooms[room.id] = raw;
      rawArea.rooms.push(room.id);
      if (room.hash) mpRoomDbHashToRoomId[room.hash] = room.id;
    }

    const xs = (area.rooms || []).map(r => r.x), ys = (area.rooms || []).map(r => r.y), zs = (area.rooms || []).map(r => r.z);
    if (xs.length) {
      rawArea.max_x = Math.max(...xs); rawArea.min_x = Math.min(...xs);
      // Mudlet calcSpan() neguje Y: min_y = -max(room.y), max_y = -min(room.y)
      rawArea.max_y = -Math.min(...ys); rawArea.min_y = -Math.max(...ys);
      rawArea.max_z = Math.max(...zs); rawArea.min_z = Math.min(...zs);
      rawArea.span = [rawArea.max_x - rawArea.min_x, rawArea.max_y - rawArea.min_y, rawArea.max_z - rawArea.min_z];
      const uniqueZ = [...new Set(zs)].sort((a, b) => a - b);
      rawArea.zLevels = uniqueZ;
      for (const z of uniqueZ) {
        const rz = (area.rooms || []).filter(r => r.z === z);
        rawArea.xmaxForZ[z] = Math.max(...rz.map(r => r.x));
        rawArea.ymaxForZ[z] = -Math.min(...rz.map(r => r.y));
        rawArea.xminForZ[z] = Math.min(...rz.map(r => r.x));
        rawArea.yminForZ[z] = -Math.max(...rz.map(r => r.y));
      }
    }
    areas[areaId] = rawArea;
    labels[areaId] = (area.labels || []).map(buildLabel);
  }

  // areaNames[-1] = map name (from arkmap; do not overwrite meta.map_name)
  // Area -1 is "Default Area" in Mudlet — it must be preserved from arkmap.areas
  // Overwriting it here produced a wrong name after the round-trip

  // mAreaExits (exits between areas)
  // Mudlet format: QMultiMap<int srcRoomId, QPair<int targetRoomId, int dirCode>>
  // dirCode: 1–12 = standard (DIRS[].idx), 13 = DIR_OTHER (special exit)
  for (const [areaId, rawArea] of Object.entries(areas)) {
    const srcAreaId = parseInt(areaId);
    const areaRoomSet = new Set(rawArea.rooms);
    const exits = {};
    for (const roomId of rawArea.rooms) {
      const room = rooms[roomId];
      // Standard exits (dir 1–12)
      for (const { long, idx } of DIRS) {
        const target = room[long];
        if (target > 0 && !areaRoomSet.has(target)) {
          if (!exits[roomId]) exits[roomId] = [];
          exits[roomId].push([target, idx]);
        }
      }
      // Special exits (dir 13 = DIR_OTHER)
      for (const [, tid] of Object.entries(room.mSpecialExits ?? {})) {
        if (tid > 0 && !areaRoomSet.has(tid)) {
          if (!exits[roomId]) exits[roomId] = [];
          exits[roomId].push([tid, 13]);
        }
      }
    }
    rawArea.mAreaExits = exits;
  }

  const dat = {
    version: 20, envColors: arkmap.colors?.env_colors ?? {}, areaNames,
    mCustomEnvColors: Object.fromEntries(
      Object.entries(arkmap.colors?.custom_env_colors ?? {})
        .filter(([k, v]) => {
          const id = parseInt(k);
          // envId outside the ANSI 1-255 range -> always custom
          if (id < 1 || id > 255) return true;
          // envId in 1-255: include only if the value differs from the standard ANSI palette
          const ansi = ansiPaletteRgb(id);
          if (!ansi) return true;
          const arr = Array.isArray(v) ? v : [v.r ?? 0, v.g ?? 0, v.b ?? 0];
          return arr[0] !== ansi[0] || arr[1] !== ansi[1] || arr[2] !== ansi[2];
        })
        .map(([k, v]) => [k, toQColor(v)])
    ),
    mpRoomDbHashToRoomId, mUserData: arkmap.meta?.user_data ?? {},
    mapSymbolFont: toQFont(arkmap.meta?.symbol_font),
    mapFontFudgeFactor: arkmap.meta?.symbol_font_fudge_factor ?? 1.0,
    useOnlyMapFont: arkmap.meta?.use_only_map_font ?? false,
    areas, mRoomIdHash: arkmap.meta?.room_id_hash ?? {}, labels, rooms,
  };

  return writeMudletDat(dat);
}

export { arkmapToDat };
