// GENERATED by scripts/extract.mjs — DO NOT EDIT.
// Source: Isithunzi000/arkadia-web_standalone-arkmap_studio/arkmap_studio.html @ 24bd9022895753779758e5c58286565c76d85d19 (lines 10590-10606)
// Bodies are byte-verbatim from the app; only import/export plumbing is added.

function _canonicalizeMapForSave(map) {
  if (map.areas) {
    map.areas.sort((a, b) => a.id - b.id);
    for (const area of map.areas) {
      if (area.rooms) {
        area.rooms.sort((a, b) => a.id - b.id);
        for (const room of area.rooms) {
          if (room.stubs)              room.stubs.sort();
          if (room.exit_locks)         room.exit_locks.sort();
          if (room.special_exit_locks) room.special_exit_locks.sort();
          delete room.area;  // internal field, not in spec
        }
      }
      if (area.labels) area.labels.sort((a, b) => a.id - b.id);
    }
  }
}

export { _canonicalizeMapForSave };
