// GENERATED by scripts/extract.mjs — DO NOT EDIT.
// Source: Isithunzi000/arkadia-web_standalone-arkmap_studio/arkmap_studio.html @ 24bd9022895753779758e5c58286565c76d85d19 (lines 4234-4278)
// Bodies are byte-verbatim from the app; only import/export plumbing is added.

// ── constants.js ──
// Standard exit directions: shorthand -> full name and Mudlet 1-based index
// Order matching the Mudlet TMap.h DIR_ constants:
// DIR_NORTH=1, DIR_NORTHEAST=2, DIR_NORTHWEST=3, DIR_EAST=4,
// DIR_WEST=5,  DIR_SOUTH=6,    DIR_SOUTHEAST=7, DIR_SOUTHWEST=8,
// DIR_UP=9,    DIR_DOWN=10,    DIR_IN=11,        DIR_OUT=12
const DIRS = [
  { short: 'n',    long: 'north',     idx: 1  },
  { short: 'ne',   long: 'northeast', idx: 2  },
  { short: 'nw',   long: 'northwest', idx: 3  },
  { short: 'e',    long: 'east',      idx: 4  },
  { short: 'w',    long: 'west',      idx: 5  },
  { short: 's',    long: 'south',     idx: 6  },
  { short: 'se',   long: 'southeast', idx: 7  },
  { short: 'sw',   long: 'southwest', idx: 8  },
  { short: 'up',   long: 'up',        idx: 9  },
  { short: 'down', long: 'down',      idx: 10 },
  { short: 'in',   long: 'in',        idx: 11 },
  { short: 'out',  long: 'out',       idx: 12 },
];

const DIR_BY_SHORT = Object.fromEntries(DIRS.map(d => [d.short, d]));
const DIR_BY_LONG  = Object.fromEntries(DIRS.map(d => [d.long,  d]));
const DIR_BY_IDX   = Object.fromEntries(DIRS.map(d => [d.idx,   d]));

// Mudlet door int values
const DOOR_INT = { open: 1, closed: 2, locked: 3 };
const DOOR_STR = Object.fromEntries(Object.entries(DOOR_INT).map(([k, v]) => [v, k]));
// Kolory drzwi wg ExitRenderer/SpecialExitStyle/InnerExitStyle Delwinga (ZAD 2)
const DOOR_RGB = { open: 'rgb(10,155,10)', closed: 'rgb(226,205,59)', locked: 'rgb(155,10,10)' };

// Mudlet custom line style int values
const LINE_INT = { solid: 1, dash: 2, dot: 3, dash_dot: 4, dash_dot_dot: 5 };
const LINE_STR = Object.fromEntries(Object.entries(LINE_INT).map(([k, v]) => [v, k]));

const FORMAT         = 'arkmap';
const FORMAT_VERSION = 2;   // v2 envelope (D1): format_version + checksums at top level; v1 files rejected
// P-LOCK-3: complete set of v2-envelope top-level keys (spec: areas/checksums/colors/
// format/format_version/meta). Foreign keys are preserved (D3) but flagged on load.
const _ARKMAP_TOP_KEYS = new Set(['format', 'format_version', 'meta', 'colors', 'areas', 'checksums']);

// (CRC-32 removed in v1.45.0 — the only consumer (.arkdelta checksums) migrated to XXH3-64,
//  unified with the .arkmap checksum engine; stableStringify remains the delta-content canonization)

export { DIRS, DIR_BY_SHORT, DIR_BY_LONG, DIR_BY_IDX, DOOR_INT, DOOR_STR, DOOR_RGB, LINE_INT, LINE_STR, FORMAT, FORMAT_VERSION, _ARKMAP_TOP_KEYS };
