// GENERATED by scripts/extract.mjs — DO NOT EDIT.
// Source: Isithunzi000/arkadia-web_standalone-arkmap_studio/arkmap_studio.html @ 24bd9022895753779758e5c58286565c76d85d19 (lines 8049-8054)
// Bodies are byte-verbatim from the app; only import/export plumbing is added.

// ─── OPPOSITE — opposite-direction map (Pass 68, S8) ─────────────────────────
const OPPOSITE = {
  n:'s', s:'n', e:'w', w:'e',
  ne:'sw', sw:'ne', nw:'se', se:'nw',
  up:'down', down:'up', in:'out', out:'in'
};

export { OPPOSITE };
