// GENERATED by scripts/extract.mjs — DO NOT EDIT.
// Source: Isithunzi000/arkadia-web_standalone-arkmap_studio/arkmap_studio.html @ 24bd9022895753779758e5c58286565c76d85d19 (lines 19357-19413)
// Bodies are byte-verbatim from the app; only import/export plumbing is added.

import { OPPOSITE } from './opposite.js';

function _findMissingSuppressors(roomById, roomArea) {
  const missing = [];
  for (const A of Object.values(roomById)) {
    for (const [dir, cl] of Object.entries(A.custom_lines || {})) {
      if (!Array.isArray(cl.points)) continue;   // null-safety — skip broken entries (non-array)
      if (cl.points.length === 0) continue;      // A is a suppressor — skip
      if (dir === 'up' || dir === 'down' || dir === 'in' || dir === 'out') continue; // inner-exit -> triangle, not a line; suppressor never needed
      const targetId = A.exits?.[dir];            // exits[] only, not special_exits
      if (targetId === undefined) continue;        // orphan CL — skip
      // audit T4/Q5: dead guard `targetId === -1` removed — the model does not hold -1 (stubs live in room.stubs)
      const B = roomById[targetId];
      if (!B) continue;                            // target does not exist — skip
      if (roomArea[A.id] !== roomArea[B.id]) continue; // cross-area — skip
      if (A.z !== B.z) continue;                   // cross-Z -> the other room is not rendered on this level, no double line
      const opp = OPPOSITE[dir];
      if (!opp) continue;                          // unknown direction — skip
      // A suppressor is needed ONLY when B has a return exit to A in direction opp
      // (because only then does Mudlet draw a default line from B that must be suppressed)
      if (B.exits?.[opp] !== A.id) continue;       // B has no reciprocal exit — skip
      // Arc 37 (PRACA 13): the old multi-edge skip (otherDefaultEdge) was removed — it relied
      // on PAIR dedup from Delwing's renderer (exitsRendered). Our renderer
      // (drawExits) draws default lines per (room, direction) and each direction suppresses
      // its own custom_line — with multi-edge A<->B the B->A (opp) line is drawn anyway,
      // so the suppressor is still NEEDED. The cross-area skip above STAYS:
      // a deliberate decision — cross-area exits render as arrows/labels,
      // not as default lines, so there is no double line there.
      const bcl = B.custom_lines?.[opp];
      if (!bcl) {                                  // no CL at all in direction opp -> suppressor needed
        missing.push({ roomA: A.id, dir, roomB: B.id, oppDir: opp, sourceCL: cl });
      }
    }
  }
  return missing;
}
// checkSuppressors() — application state (editing / save gate / validation button).
function checkSuppressors() {
  return _findMissingSuppressors(state.roomById, state.roomArea);
}
// checkSuppressorsInMap — variant for a parsed map BEFORE applyMap (val-modal
// on load, Arc 29). Read-only: builds light ad-hoc indexes and NEVER mutates
// the map (the object goes to applyMap afterwards). NEVER throws — skips malformed
// rooms; the load must not be toppled by this check.
function checkSuppressorsInMap(map) {
  try {
    const roomById = {}, roomArea = {};
    const areas = (map && Array.isArray(map.areas)) ? map.areas : [];
    for (const area of areas) {
      if (!area || !Array.isArray(area.rooms)) continue;
      for (const r of area.rooms) {
        if (!r || r.id === undefined || r.id === null) continue;
        roomById[r.id] = r;
        roomArea[r.id] = area.id;
      }
    }
    return _findMissingSuppressors(roomById, roomArea);
  } catch (e) { return []; }
}

export { checkSuppressorsInMap, _findMissingSuppressors };
