// GENERATED by scripts/extract.mjs — DO NOT EDIT.
// Source: Isithunzi000/arkadia-web_standalone-arkmap_studio/arkmap_studio.html @ 24bd9022895753779758e5c58286565c76d85d19 (lines 19357-19413)
// Bodies are byte-verbatim from the app; only import/export plumbing is added.

import { OPPOSITE } from './opposite.js';

function _findMissingSuppressors(roomById, roomArea) {
  const missing = [];
  for (const A of Object.values(roomById)) {
    for (const [dir, cl] of Object.entries(A.custom_lines || {})) {
      if (!Array.isArray(cl.points)) continue;   // null-safety — pomiń zepsute wpisy (nie-tablica)
      if (cl.points.length === 0) continue;      // A jest suppresorem — skip
      if (dir === 'up' || dir === 'down' || dir === 'in' || dir === 'out') continue; // inner-exit → trójkąt, nie linia; suppressor nigdy niepotrzebny
      const targetId = A.exits?.[dir];            // tylko exits[], nie special_exits
      if (targetId === undefined) continue;        // orphan CL — skip
      // audyt T4/Q5: martwy guard `targetId === -1` usuniety — model nie trzyma -1 (stuby sa w room.stubs)
      const B = roomById[targetId];
      if (!B) continue;                            // target nie istnieje — skip
      if (roomArea[A.id] !== roomArea[B.id]) continue; // cross-area — skip
      if (A.z !== B.z) continue;                   // cross-Z → drugi pokój nierenderowany na tym poziomie, brak podwójnej linii
      const opp = OPPOSITE[dir];
      if (!opp) continue;                          // nieznany kierunek — skip
      // Suppressor potrzebny TYLKO gdy B ma wyjście powrotne do A w kierunku opp
      // (bo tylko wtedy Mudlet rysuje domyślną linię z B, którą trzeba stłumić)
      if (B.exits?.[opp] !== A.id) continue;       // B nie ma reciprocal exit — skip
      // Arc 37 (PRACA 13): dawny skip multi-edge (otherDefaultEdge) usuniety — opieral
      // sie na dedupie PAR pokoi z renderera Delwinga (exitsRendered). Nasz renderer
      // (drawExits) rysuje linie domyslne per (pokoj, kierunek) i kazdy kierunek tlumi
      // wlasna custom_line — przy multi-edge A↔B linia B→A (opp) i tak powstaje,
      // wiec suppressor jest nadal POTRZEBNY. Skip cross-area powyzej ZOSTAJE:
      // swiadoma decyzja — wyjscia cross-area renderuja sie jako strzalki/etykiety,
      // nie jako domyslne linie, wiec podwojnej linii tam nie ma.
      const bcl = B.custom_lines?.[opp];
      if (!bcl) {                                  // brak jakiejkolwiek CL w kierunku opp → suppressor potrzebny
        missing.push({ roomA: A.id, dir, roomB: B.id, oppDir: opp, sourceCL: cl });
      }
    }
  }
  return missing;
}
// checkSuppressors() — stan aplikacji (edycja / bramka zapisu / przycisk walidacji).
function checkSuppressors() {
  return _findMissingSuppressors(state.roomById, state.roomArea);
}
// checkSuppressorsInMap — wariant dla sparsowanej mapy PRZED applyMap (val-modal
// przy loadzie, Arc 29). Read-only: buduje lekkie indeksy ad hoc i NIGDY nie mutuje
// mapy (obiekt idzie potem do applyMap). NIGDY nie rzuca — malformed pokoje pomija,
// load nie moze sie wywrocic przez ten check.
function checkSuppressorsInMap(map) {
  try {
    const roomById = {}, roomArea = {};
    const areas = (map && Array.isArray(map.areas)) ? map.areas : [];
    for (const area of areas) {
      if (!area || !Array.isArray(area.rooms)) continue;
      for (const r of area.rooms) {
        if (!r || r.id === undefined || r.id === null) continue;
        roomById[r.id] = r;
        roomArea[r.id] = area.id;
      }
    }
    return _findMissingSuppressors(roomById, roomArea);
  } catch (e) { return []; }
}

export { checkSuppressorsInMap, _findMissingSuppressors };
